In [1]:
import numpy as np

In [3]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
##suma de matrices
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
SUMA=A+B
print(f'la suma de matrices es :{SUMA}')



la suma de matrices es :[[ 6  8]
 [10 12]]


In [4]:
producto=np.dot(A,B)
print('result in prod ',producto)

result in prod  [[19 22]
 [43 50]]


In [6]:
determinante_A=np.linalg.det(A)
print('determinandte de A es : ',determinante_A)
determinante_B=np.linalg.det(B)
print('determinandte de A es : ',determinante_B)

determinandte de A es :  -2.0000000000000004
determinandte de A es :  -2.000000000000005


In [7]:

inversa_a=np.linalg.inv(A)
inversa_b=np.linalg.inv(B)

print('inversa de a ',inversa_a)
print('inversa de b ',inversa_b)

inversa de a  [[-2.   1. ]
 [ 1.5 -0.5]]
inversa de b  [[-4.   3. ]
 [ 3.5 -2.5]]


In [8]:
valores_propios, vectores_propios = np.linalg.eig(A)
print("Valores propios de A:\n", valores_propios)
print("Vectores propios de A:\n", vectores_propios)

Valores propios de A:
 [-0.37228132  5.37228132]
Vectores propios de A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [9]:
B = np.array([1, 2])
X = np.linalg.solve(A, B)
print("Solución del sistema AX = B:\n", X)


Solución del sistema AX = B:
 [0.  0.5]


INDEX AND SLICING

In [12]:

array = np.arange(10, 1210, 10)
bol_idx=array>25
print(bol_idx)

[False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True]


In [13]:
index=[1,2,3,4,5,6,7,8,9]
print(array[index])

[ 20  30  40  50  60  70  80  90 100]


In [15]:
array=np.random.randint(1,10,size=(3,3))
print(array)
print(array[0,1])

[[6 8 1]
 [3 5 3]
 [8 6 7]]
8


In [16]:
print(array[:2,:2])

[[6 8]
 [3 5]]


BROADCASTING

In [24]:
prices=np.array([100,200,300])
discount=np.array([0.9])
discount_prices=prices * discount
print(discount_prices)

[ 90. 180. 270.]


In [26]:
prices=np.random.randint(100,500 , size=(3,3))
discount=np.array([10,20,30])
discount_price=prices + discount
print(prices)
print(discount_price)


[[206 304 431]
 [203 460 341]
 [184 489 399]]
[[216 324 461]
 [213 480 371]
 [194 509 429]]


In [35]:
array=np.array([1,2,3,4,5,6,7,8,9])
print(np.all(array>0))
print(np.any(array<10))

True
True


In [36]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
result = np.concatenate((a, b))
print(result)

[ 1  2  3  4  5  6  7  8  9 10]


In [38]:
# Define two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Use vstack to vertically stack the arrays
vertical_stack = np.vstack((array1, array2))
print("Vertical Stack:")
print(vertical_stack)

# Use hstack to horizontally stack the arrays
horizontal_stack = np.hstack((array1, array2))
print("Horizontal Stack:")
print(horizontal_stack)

Vertical Stack:
[[1 2 3]
 [4 5 6]]
Horizontal Stack:
[1 2 3 4 5 6]


In [39]:
import numpy as np

# Create an array using arange for values 1 to 10
array_arange = np.arange(1, 11)
print("Array using arange:")
print(array_arange)

# Create another array using split
array_split = np.split(array_arange, 2)
print("Array using split:")
print(array_split)

Array using arange:
[ 1  2  3  4  5  6  7  8  9 10]
Array using split:
[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [40]:
#items unique and counts
survey_responses = np.array(['good', 'good', 'good', 'fail', 'excellent'])
unique_elements,counts=np.unique(survey_responses,return_counts=True)
print(unique_elements)
print(counts)

['excellent' 'fail' 'good']
[1 1 3]


In [69]:
# Swap the first and last elements in the array
print(array)
array[0], array[-1] = array[-1], array[0]

# Swap the second and second-to-last elements in the array
array[1], array[-2] = array[-2], array[1]

# Print the modified array
print(array)

[1 2 3 4 5 6 7 8 9]
[9 8 3 4 5 6 7 2 1]


reshape and transoformation 

In [3]:
import numpy as np
# Case 1: Reshape a 1D array to a 2D array
array1 = np.array([1, 2, 3, 4, 5, 6])
reshaped_array1 = array1.reshape(2, 3)
print("Reshaped Array 1:")
print(reshaped_array1)

# Case 2: Reshape a 2D array to a 1D array
array2 = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_array2 = array2.reshape(-1)
print("Reshaped Array 2:")
print(reshaped_array2)

# Case 3: Reshape a 2D array to a 3D array
array3 = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_array3 = array3.reshape(2, 1, 3)
print("Reshaped Array 3:")
print(reshaped_array3)

# Case 4: Reshape a 3D array to a 2D array
array4 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
reshaped_array4 = array4.reshape(2, 6)
print("Reshaped Array 4:")
print(reshaped_array4)

Reshaped Array 1:
[[1 2 3]
 [4 5 6]]
Reshaped Array 2:
[1 2 3 4 5 6]
Reshaped Array 3:
[[[1 2 3]]

 [[4 5 6]]]
Reshaped Array 4:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


CASE PRACTICE

In [5]:
# Paso 1: Crear arrays con datos de ventas mensuales
meses = np.array(['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'])
ventas_A = np.array([150, 200, 250, 300, 220, 210, 180, 190, 230, 240, 280, 300])
ventas_B = np.array([180, 210, 230, 250, 270, 260, 240, 250, 270, 290, 310, 330])
ventas_C = np.array([200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420])

# Calculate the total sales for each month
total_sales = ventas_A + ventas_B + ventas_C

# Calculate the average sales for each month
average_sales = (ventas_A + ventas_B + ventas_C) / 3

# Find the month with the highest sales
max_sales_month = meses[np.argmax(total_sales)]

# Find the month with the lowest sales
min_sales_month = meses[np.argmin(total_sales)]

# Reshape the arrays
reshaped_ventas_A = ventas_A.reshape(12, 1)
reshaped_ventas_B = ventas_B.reshape(12, 1)
reshaped_ventas_C = ventas_C.reshape(12, 1)

# Transpose the arrays
transposed_ventas_A = ventas_A.T
transposed_ventas_B = ventas_B.T
transposed_ventas_C = ventas_C.T

# Find the unique elements in the arrays
unique_ventas_A = np.unique(ventas_A)
unique_ventas_B = np.unique(ventas_B)
unique_ventas_C = np.unique(ventas_C)

# Perform mathematical operations on the arrays
sum_ventas_A = np.sum(ventas_A)
sum_ventas_B = np.sum(ventas_B)
sum_ventas_C = np.sum(ventas_C)

mean_ventas_A = np.mean(ventas_A)
mean_ventas_B = np.mean(ventas_B)
mean_ventas_C = np.mean(ventas_C)

max_ventas_A = np.max(ventas_A)
max_ventas_B = np.max(ventas_B)
max_ventas_C = np.max(ventas_C)

min_ventas_A = np.min(ventas_A)
min_ventas_B = np.min(ventas_B)
min_ventas_C = np.min(ventas_C)
print("Name: array1")
print("Type: numpy.ndarray")
print("Value:", array1)
print()

print("Name: array2")
print("Type: numpy.ndarray")
print("Value:", array2)
print()

print("Name: array3")
print("Type: numpy.ndarray")
print("Value:", array3)
print()

print("Name: array4")
print("Type: numpy.ndarray")
print("Value:", array4)
print()

print("Name: average_sales")
print("Type: numpy.ndarray")
print("Value:", average_sales)
print()

print("Name: max_sales_month")
print("Type: numpy.str_")
print("Value:", max_sales_month)
print()

print("Name: max_ventas_A")
print("Type: numpy.int64")
print("Value:", max_ventas_A)
print()

print("Name: max_ventas_B")
print("Type: numpy.int64")
print("Value:", max_ventas_B)
print()

print("Name: max_ventas_C")
print("Type: numpy.int64")
print("Value:", max_ventas_C)
print()

print("Name: mean_ventas_A")
print("Type: numpy.float64")
print("Value:", mean_ventas_A)
print()

print("Name: mean_ventas_B")
print("Type: numpy.float64")
print("Value:", mean_ventas_B)
print()

print("Name: mean_ventas_C")
print("Type: numpy.float64")
print("Value:", mean_ventas_C)
print()

print("Name: meses")
print("Type: numpy.ndarray")
print("Value:", meses)
print()

print("Name: min_sales_month")
print("Type: numpy.str_")
print("Value:", min_sales_month)
print()

print("Name: min_ventas_A")
print("Type: numpy.int64")
print("Value:", min_ventas_A)
print()

print("Name: min_ventas_B")
print("Type: numpy.int64")
print("Value:", min_ventas_B)
print()

print("Name: min_ventas_C")
print("Type: numpy.int64")
print("Value:", min_ventas_C)
print()

print("Name: reshaped_array1")
print("Type: numpy.ndarray")
print("Value:", reshaped_array1)
print()

print("Name: reshaped_array2")
print("Type: numpy.ndarray")
print("Value:", reshaped_array2)
print()

print("Name: reshaped_array3")
print("Type: numpy.ndarray")
print("Value:", reshaped_array3)
print()

print("Name: reshaped_array4")
print("Type: numpy.ndarray")
print("Value:", reshaped_array4)
print()

print("Name: reshaped_ventas_A")
print("Type: numpy.ndarray")
print("Value:", reshaped_ventas_A)
print()

print("Name: reshaped_ventas_B")
print("Type: numpy.ndarray")
print("Value:", reshaped_ventas_B)
print()

print("Name: reshaped_ventas_C")
print("Type: numpy.ndarray")
print("Value:", reshaped_ventas_C)
print()

print("Name: sum_ventas_A")
print("Type: numpy.int64")
print("Value:", sum_ventas_A)
print()

print("Name: sum_ventas_B")
print("Type: numpy.int64")
print("Value:", sum_ventas_B)
print()

print("Name: sum_ventas_C")
print("Type: numpy.int64")
print("Value:", sum_ventas_C)
print()

print("Name: total_sales")
print("Type: numpy.ndarray")
print("Value:", total_sales)
print()

print("Name: transposed_ventas_A")
print("Type: numpy.ndarray")
print("Value:", transposed_ventas_A)
print()

print("Name: transposed_ventas_B")
print("Type: numpy.ndarray")
print("Value:", transposed_ventas_B)
print()

print("Name: transposed_ventas_C")
print("Type: numpy.ndarray")
print("Value:", transposed_ventas_C)
print()

print("Name: unique_ventas_A")
print("Type: numpy.ndarray")
print("Value:", unique_ventas_A)
print()

print("Name: unique_ventas_B")
print("Type: numpy.ndarray")
print("Value:", unique_ventas_B)
print()

print("Name: unique_ventas_C")
print("Type: numpy.ndarray")
print("Value:", unique_ventas_C)
print()

print("Name: ventas_A")
print("Type: numpy.ndarray")
print("Value:", ventas_A)
print()

print("Name: ventas_B")
print("Type: numpy.ndarray")
print("Value:", ventas_B)
print()

print("Name: ventas_C")
print("Type: numpy.ndarray")
print("Value:", ventas_C)
print()


Name: array1
Type: numpy.ndarray
Value: [1 2 3 4 5 6]

Name: array2
Type: numpy.ndarray
Value: [[1 2 3]
 [4 5 6]]

Name: array3
Type: numpy.ndarray
Value: [[1 2 3]
 [4 5 6]]

Name: array4
Type: numpy.ndarray
Value: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Name: average_sales
Type: numpy.ndarray
Value: [176.66666667 210.         240.         270.         256.66666667
 256.66666667 246.66666667 260.         286.66666667 303.33333333
 330.         350.        ]

Name: max_sales_month
Type: numpy.str_
Value: Diciembre

Name: max_ventas_A
Type: numpy.int64
Value: 300

Name: max_ventas_B
Type: numpy.int64
Value: 330

Name: max_ventas_C
Type: numpy.int64
Value: 420

Name: mean_ventas_A
Type: numpy.float64
Value: 229.16666666666666

Name: mean_ventas_B
Type: numpy.float64
Value: 257.5

Name: mean_ventas_C
Type: numpy.float64
Value: 310.0

Name: meses
Type: numpy.ndarray
Value: ['Enero' 'Febrero' 'Marzo' 'Abril' 'Mayo' 'Junio' 'Julio' 'Agosto'
 'Septiembre' 'Octubre' 'Noviembre'