In [1]:
import numpy as np

In [3]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
##suma de matrices
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
SUMA=A+B
print(f'la suma de matrices es :{SUMA}')



la suma de matrices es :[[ 6  8]
 [10 12]]


In [4]:
producto=np.dot(A,B)
print('result in prod ',producto)

result in prod  [[19 22]
 [43 50]]


In [6]:
determinante_A=np.linalg.det(A)
print('determinandte de A es : ',determinante_A)
determinante_B=np.linalg.det(B)
print('determinandte de A es : ',determinante_B)

determinandte de A es :  -2.0000000000000004
determinandte de A es :  -2.000000000000005


In [7]:

inversa_a=np.linalg.inv(A)
inversa_b=np.linalg.inv(B)

print('inversa de a ',inversa_a)
print('inversa de b ',inversa_b)

inversa de a  [[-2.   1. ]
 [ 1.5 -0.5]]
inversa de b  [[-4.   3. ]
 [ 3.5 -2.5]]


In [8]:
valores_propios, vectores_propios = np.linalg.eig(A)
print("Valores propios de A:\n", valores_propios)
print("Vectores propios de A:\n", vectores_propios)

Valores propios de A:
 [-0.37228132  5.37228132]
Vectores propios de A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [9]:
B = np.array([1, 2])
X = np.linalg.solve(A, B)
print("Solución del sistema AX = B:\n", X)


Solución del sistema AX = B:
 [0.  0.5]


INDEX AND SLICING

In [12]:

array = np.arange(10, 1210, 10)
bol_idx=array>25
print(bol_idx)

[False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True]


In [13]:
index=[1,2,3,4,5,6,7,8,9]
print(array[index])

[ 20  30  40  50  60  70  80  90 100]


In [15]:
array=np.random.randint(1,10,size=(3,3))
print(array)
print(array[0,1])

[[6 8 1]
 [3 5 3]
 [8 6 7]]
8


In [16]:
print(array[:2,:2])

[[6 8]
 [3 5]]


BROADCASTING

In [24]:
prices=np.array([100,200,300])
discount=np.array([0.9])
discount_prices=prices * discount
print(discount_prices)

[ 90. 180. 270.]


In [26]:
prices=np.random.randint(100,500 , size=(3,3))
discount=np.array([10,20,30])
discount_price=prices + discount
print(prices)
print(discount_price)


[[206 304 431]
 [203 460 341]
 [184 489 399]]
[[216 324 461]
 [213 480 371]
 [194 509 429]]


In [35]:
array=np.array([1,2,3,4,5,6,7,8,9])
print(np.all(array>0))
print(np.any(array<10))

True
True


In [36]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
result = np.concatenate((a, b))
print(result)

[ 1  2  3  4  5  6  7  8  9 10]


In [38]:
# Define two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Use vstack to vertically stack the arrays
vertical_stack = np.vstack((array1, array2))
print("Vertical Stack:")
print(vertical_stack)

# Use hstack to horizontally stack the arrays
horizontal_stack = np.hstack((array1, array2))
print("Horizontal Stack:")
print(horizontal_stack)

Vertical Stack:
[[1 2 3]
 [4 5 6]]
Horizontal Stack:
[1 2 3 4 5 6]


In [39]:
import numpy as np

# Create an array using arange for values 1 to 10
array_arange = np.arange(1, 11)
print("Array using arange:")
print(array_arange)

# Create another array using split
array_split = np.split(array_arange, 2)
print("Array using split:")
print(array_split)

Array using arange:
[ 1  2  3  4  5  6  7  8  9 10]
Array using split:
[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]


In [40]:
#items unique and counts
survey_responses = np.array(['good', 'good', 'good', 'fail', 'excellent'])
unique_elements,counts=np.unique(survey_responses,return_counts=True)
print(unique_elements)
print(counts)

['excellent' 'fail' 'good']
[1 1 3]


In [69]:
# Swap the first and last elements in the array
print(array)
array[0], array[-1] = array[-1], array[0]

# Swap the second and second-to-last elements in the array
array[1], array[-2] = array[-2], array[1]

# Print the modified array
print(array)

[1 2 3 4 5 6 7 8 9]
[9 8 3 4 5 6 7 2 1]
